version: '3'
services:
  barotrauma-server:
    build: ./barotrauma
    volumes:
      - barotrauma:/home/steam/steamcmd/barotrauma

  frpc:
    image: natfrp/frpc
    command: ["-f",""] #put your key here

volumes:
  barotrauma:
